_wandb:
    value:
        cli_version: 0.18.3
        m: []
        python_version: 3.8.19
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 1
                - 16
                - 23
                - 55
            "4": 3.8.19
            "5": 0.18.3
            "8":
                - 5
            "12": 0.18.3
            "13": linux-x86_64
batch_size:
    value: 72
lr:
    value: 0.0001
n_restart:
    value: 3
niters:
    value: 15
ode_method:
    value: dopri5
shuffle:
    value: true
test_freq:
    value: 100
